import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { NavBar } from '@/components';

const poppins = Poppins({ subsets: ['latin'], weight: '600' });

export const metadata: Metadata = {
  title: "Jose's home page",
  description: 'Generated by Vercel',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
